---
apiVersion: v1
kind: Secret
metadata:
  name: michaeljohn32-michaeljohn32-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/michaeljohn32-gateway-gitops
